version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: misc
    labels:
      - 'type: technical'
      - 'ops'

  - package-ecosystem: composer
    directory: /backend
    schedule:
      interval: monthly
    commit-message:
      prefix: misc
    labels:
      - 'type: technical'
      - 'backend'
    versioning-strategy: increase
    groups:
      symfony:
        patterns:
          - 'symfony/*'
        exclude-patterns:
          - symfony/flex
          - symfony/monolog-bundle

      doctrine:
        patterns:
          - 'doctrine/*'

      phpstan:
        patterns:
          - 'phpstan/*'
    # Temporarily disable version updates for Composer
    open-pull-requests-limit: 0

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: monthly
    commit-message:
      prefix: misc
    labels:
      - 'type: technical'
      - 'frontend'
    versioning-strategy: increase
    # Temporarily disable version updates for npm/yarn dependencies
    open-pull-requests-limit: 0
