version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: misc
    labels:
      - 'type: technical'

  - package-ecosystem: composer
    directory: /backend
    schedule:
      interval: monthly
    commit-message:
      prefix: misc
    labels:
      - 'type: technical'
    versioning-strategy: increase
    groups:
      symfony:
        patterns:
          - 'symfony/*'
        exclude-patterns:
          - symfony/flex
          - symfony/monolog-bundle

      doctrine:
        patterns:
          - 'doctrine/*'

      phpstan:
        patterns:
          - 'phpstan/*'
