services:
    backend:
        image: ${PROJECT_NAME}-backend:dev
        build:
            context: ./../
            dockerfile: ./docker/backend/Dockerfile
            target: development
            args:
                USER_UID: ${USER_UID}
                PHP_VERSION: ${PHP_VERSION}
            cache_from:
                - ${PROJECT_NAME}-backend:dev
        environment:
            # Application
            APP_ENV: dev
            COMPOSER_MEMORY_LIMIT: -1
            POSTGRES_VERSION: ${POSTGRES_VERSION}
            # Debug
            XDEBUG_MODE: ${XDEBUG_MODE:-off}
            XDEBUG_SESSION: PHPSTORM # For CLI debugging
        ports:
            - "8080:8000"
            - "8989:8989"
        volumes:
            - ./../backend:/var/www/app
        extra_hosts:
            - host.docker.internal:host-gateway

    postgres:
        image: postgres:${POSTGRES_VERSION}-alpine
        ports:
            - "8585:5432"
        volumes:
            - data-postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: app
            POSTGRES_PASSWORD: postgres

    adminer:
        image: adminer:${ADMINER_VERSION}
        ports:
            - "8282:8080"
        environment:
            ADMINER_DEFAULT_SERVER: postgres

    maildev:
        image: maildev/maildev:latest
        command: bin/maildev --smtp 25 --hide-extensions STARTTLS -v
        ports:
            - "8383:1080"

    redis:
        image: redis:${REDIS_VERSION}-alpine

    redis-commander:
        image: rediscommander/redis-commander:latest
        ports:
            - "8484:8081"
        environment:
            REDIS_HOSTS: local:redis:6379

volumes:
    data-postgres:
