name: CI image

on:
  push:
    branches:
      - main
    paths:
      - 'docker/backend/**/*'
  schedule:
    - cron: '30 2 * * *'

jobs:
  build-ci-image:
    name: Build CI image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      CI_IMAGE: ${{ vars.CI_REGISTRY }}/${{ github.repository }}/ci

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Packages registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.CI_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.CI_IMAGE }}
          tags: php-${{ vars.PHP_VERSION }}
          labels: |
              org.opencontainers.image.description=Custom PHP ${{ vars.PHP_VERSION }} CI image for ${{ github.repository }}

      - name: Build and Publish
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/backend/Dockerfile
          target: cli
          pull: true
          cache-from: type=registry,ref=${{ steps.meta.outputs.tags }}
          cache-to: type=inline
          build-args: |
            USER_UID=1000
            PHP_VERSION=${{ vars.PHP_VERSION }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
