name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.CI_IMAGE }}:php-${{ vars.PHP_VERSION }}
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dependencies
        uses: ./.github/workflows/common/composer-install

      - name: Run PHP-CS-Fixer
        run: composer phpcs-check

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.CI_IMAGE }}:php-${{ vars.PHP_VERSION }}
      env:
        APP_ENV: test
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare test setup
        # Note: The PHPStan configuration is changed to also work in the test environment
        run: |
          sed -i -e 's/KernelDevDebugContainer/KernelTestDebugContainer/g' phpstan.dist.neon
          sed -i -e 's/var\/cache\/dev/var\/cache\/test/g' phpstan.dist.neon
          sed -i -e '/doctrine:/{N;d;}' phpstan.dist.neon

      - name: Setup dependencies
        uses: ./.github/workflows/common/composer-install
        with:
          run-scripts: true # Required to generate Symfony config cache files

      - name: Run PHPStan
        run: composer phpstan

  rector:
    name: Rector
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.CI_IMAGE }}:php-${{ vars.PHP_VERSION }}
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dependencies
        uses: ./.github/workflows/common/composer-install
        with:
          run-scripts: true # Required to generate Symfony config cache files

      - name: Run Rector
        run: composer rector -- --dry-run

  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.CI_IMAGE }}:php-${{ vars.PHP_VERSION }}
      env:
        APP_ENV: test
        XDEBUG_MODE: coverage
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dependencies
        uses: ./.github/workflows/common/composer-install

      - name: Prepare test setup
        run: |
          mkdir -p ./var/data
          bin/console doctrine:schema:update --force --env=test
          bin/console doctrine:fixtures:load --no-interaction --group=test --env=test

      - name: Run PHPUnit
        run: vendor/bin/phpunit --coverage-clover coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  php-security:
    name: PHP Security
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.CI_IMAGE }}:php-${{ vars.PHP_VERSION }}
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Symfony security check
        run: symfony security:check

      - name: Run Composer audit
        run: composer audit --locked
